#!/usr/bin/env python3

import json
import re
import unittest
from pathlib import Path

from scripts.skill_metadata import read_skill_version


class PackagingDocsTests(unittest.TestCase):
    def test_manifest_describes_prompt_first_bundle(self):
        manifest_text = Path("clawhub-zaomeng-skill/MANIFEST.md").read_text(encoding="utf-8")
        metadata_text = Path("clawhub-zaomeng-skill/.metadata.json").read_text(encoding="utf-8")
        self.assertIn("requirements.txt", manifest_text)
        self.assertIn("tools/prepare_novel_excerpt.py", manifest_text)
        self.assertIn("tools/build_prompt_payload.py", manifest_text)
        self.assertIn("tools/export_relation_graph.py", manifest_text)
        self.assertIn("人物关系图谱", manifest_text)
        self.assertNotIn("runtime/zaomeng_cli.py", manifest_text)
        self.assertNotIn("runtime/src", manifest_text)
        self.assertIn('"name": "zaomeng-skill"', metadata_text)
        self.assertIn('"version": "', metadata_text)

    def test_install_docs_describe_prompt_first_install(self):
        install_text = Path("clawhub-zaomeng-skill/INSTALL.md").read_text(encoding="utf-8")
        self.assertIn("宿主驱动的 skill 包", install_text)
        self.assertIn("requirements.txt", install_text)
        self.assertIn("tools/prepare_novel_excerpt.py", install_text)
        self.assertIn("tools/build_prompt_payload.py", install_text)
        self.assertIn("tools/export_relation_graph.py", install_text)
        self.assertNotIn("runtime/src", install_text)
        self.assertNotIn("--include-runtime", install_text)

    def test_readmes_describe_prompt_first_helpers(self):
        skill_readme = Path("clawhub-zaomeng-skill/README.md").read_text(encoding="utf-8")
        skill_readme_en = Path("clawhub-zaomeng-skill/README_EN.md").read_text(encoding="utf-8")

        self.assertIn("tools/prepare_novel_excerpt.py", skill_readme)
        self.assertIn("tools/build_prompt_payload.py", skill_readme)
        self.assertIn("tools/export_relation_graph.py", skill_readme)
        self.assertIn("requirements.txt", skill_readme)
        self.assertIn("references/chat_contract.md", skill_readme)
        self.assertIn("references/capability_index.md", skill_readme)
        self.assertIn("examples/host_workflow_example.md", skill_readme)
        self.assertIn("tools/prepare_novel_excerpt.py", skill_readme_en)
        self.assertIn("tools/build_prompt_payload.py", skill_readme_en)
        self.assertIn("tools/export_relation_graph.py", skill_readme_en)
        self.assertIn("requirements.txt", skill_readme_en)
        self.assertIn("references/chat_contract.md", skill_readme_en)
        self.assertIn("references/capability_index.md", skill_readme_en)
        self.assertIn("examples/host_workflow_example.md", skill_readme_en)
        self.assertIn("examples/chat_session_summary.example.json", skill_readme)
        self.assertIn("examples/chat_result_single_turn.example.json", skill_readme)
        self.assertIn("examples/chat_status_complete.example.json", skill_readme)
        self.assertIn("examples/chat_session_summary.example.json", skill_readme_en)
        self.assertIn("examples/chat_result_single_turn.example.json", skill_readme_en)
        self.assertIn("examples/chat_status_complete.example.json", skill_readme_en)
        self.assertNotIn("runtime/zaomeng_cli.py", skill_readme)
        self.assertNotIn("runtime/zaomeng_cli.py", skill_readme_en)

    def test_skill_docs_prioritize_host_llm_and_run_manifest_contract(self):
        clawhub_skill = Path("clawhub-zaomeng-skill/SKILL.md").read_text(encoding="utf-8")
        skill_readme = Path("clawhub-zaomeng-skill/README.md").read_text(encoding="utf-8")
        skill_readme_en = Path("clawhub-zaomeng-skill/README_EN.md").read_text(encoding="utf-8")

        self.assertIn("宿主负责实际调用 LLM", clawhub_skill)
        self.assertIn("run_manifest.json", clawhub_skill)
        self.assertIn("tools/build_prompt_payload.py", clawhub_skill)
        self.assertIn("tools/export_relation_graph.py", clawhub_skill)
        self.assertIn("tools/materialize_persona_bundle.py", clawhub_skill)
        self.assertIn("tools/init_host_run.py", clawhub_skill)
        self.assertIn("tools/update_run_progress.py", clawhub_skill)
        self.assertIn("宿主负责实际调用模型", skill_readme)
        self.assertIn("人物关系图谱", clawhub_skill)
        self.assertIn("人物关系图谱", skill_readme)
        self.assertIn("relationship graphs", skill_readme_en)
        self.assertIn("character_started", clawhub_skill)
        self.assertIn("graph_export_completed", clawhub_skill)
        self.assertIn("incremental", clawhub_skill)
        self.assertIn("existing_profiles", clawhub_skill)
        self.assertIn("artifacts.distill_context", clawhub_skill)
        self.assertIn("session-summary-out", clawhub_skill)
        self.assertIn("session-summary-out", skill_readme)
        self.assertIn("session-summary-out", skill_readme_en)
        self.assertIn("chat-result-out", clawhub_skill)
        self.assertIn("chat-status-out", clawhub_skill)
        self.assertIn("chat-result-out", skill_readme)
        self.assertIn("chat-status-out", skill_readme)
        self.assertIn("chat-result-out", skill_readme_en)
        self.assertIn("chat-status-out", skill_readme_en)
        self.assertIn("references/chat_contract.md", clawhub_skill)
        self.assertIn("references/capability_index.md", clawhub_skill)
        self.assertIn("examples/host_workflow_example.md", clawhub_skill)
        self.assertIn("五个能力", clawhub_skill)
        self.assertIn("`chat`", clawhub_skill)
        self.assertIn("examples/chat_session_summary.example.json", clawhub_skill)
        self.assertIn("examples/chat_result_single_turn.example.json", clawhub_skill)
        self.assertIn("examples/chat_status_complete.example.json", clawhub_skill)
        self.assertIn("Chat Session Summary", clawhub_skill)
        self.assertIn("会话摘要 JSON", skill_readme)
        self.assertIn("latest_responses", clawhub_skill)
        self.assertIn("self_insert", clawhub_skill)
        self.assertIn("artifacts.session_file", clawhub_skill)
        self.assertIn("zaomeng_chat_result", clawhub_skill)
        self.assertIn('capability = "chat"', clawhub_skill)
        self.assertIn("act", clawhub_skill)
        self.assertIn("insert", clawhub_skill)
        self.assertIn("observe", clawhub_skill)
        self.assertNotIn("runtime/config.yaml", clawhub_skill)
        self.assertNotIn("OPENAI_API_KEY", clawhub_skill)
        self.assertNotIn("runtime/zaomeng_cli.py", clawhub_skill)

    def test_chat_schema_examples_are_packaged_and_parseable(self):
        skill_dir = Path("clawhub-zaomeng-skill")
        summary = json.loads((skill_dir / "examples" / "chat_session_summary.example.json").read_text(encoding="utf-8"))
        result_payload = json.loads((skill_dir / "examples" / "chat_result_single_turn.example.json").read_text(encoding="utf-8"))
        status_payload = json.loads((skill_dir / "examples" / "chat_status_complete.example.json").read_text(encoding="utf-8"))

        self.assertEqual(summary["mode"], "insert")
        self.assertIn("participants", summary)
        self.assertIn("self_insert", summary)
        self.assertEqual(result_payload["kind"], "zaomeng_chat_result")
        self.assertEqual(result_payload["action"], "single_turn")
        self.assertTrue(result_payload["success"])
        self.assertEqual(status_payload["capability"], "chat")
        self.assertEqual(status_payload["status"], "complete")
        self.assertTrue(status_payload["success"])

    def test_chat_contract_reference_is_present(self):
        contract_text = Path("clawhub-zaomeng-skill/references/chat_contract.md").read_text(encoding="utf-8")
        self.assertIn("session-summary-out", contract_text)
        self.assertIn("chat-result-out", contract_text)
        self.assertIn("chat-status-out", contract_text)
        self.assertIn('kind = "zaomeng_chat_result"', contract_text)
        self.assertIn('capability = "chat"', contract_text)
        self.assertIn("examples/chat_session_summary.example.json", contract_text)

    def test_capability_index_reference_is_present(self):
        capability_text = Path("clawhub-zaomeng-skill/references/capability_index.md").read_text(encoding="utf-8")
        self.assertIn("Capability Index", capability_text)
        self.assertIn("distill", capability_text)
        self.assertIn("materialize", capability_text)
        self.assertIn("export_graph", capability_text)
        self.assertIn("verify_workflow", capability_text)
        self.assertIn("chat", capability_text)
        self.assertIn("references/chat_contract.md", capability_text)
        self.assertIn("examples/host_workflow_example.md", capability_text)

    def test_host_workflow_example_is_present(self):
        workflow_text = Path("clawhub-zaomeng-skill/examples/host_workflow_example.md").read_text(encoding="utf-8")
        self.assertIn("tools/init_host_run.py", workflow_text)
        self.assertIn("tools/build_prompt_payload.py", workflow_text)
        self.assertIn("tools/materialize_persona_bundle.py", workflow_text)
        self.assertIn("tools/export_relation_graph.py", workflow_text)
        self.assertIn("tools/verify_host_workflow.py", workflow_text)
        self.assertIn("--session-summary-out", workflow_text)
        self.assertIn("--chat-result-out", workflow_text)
        self.assertIn("--chat-status-out", workflow_text)

    def test_distillation_docs_require_multi_character_differentiation(self):
        prompt_text = Path("clawhub-zaomeng-skill/prompts/distill_prompt.md").read_text(encoding="utf-8")
        schema_text = Path("clawhub-zaomeng-skill/references/output_schema.md").read_text(encoding="utf-8")
        validation_text = Path("clawhub-zaomeng-skill/references/validation_policy.md").read_text(encoding="utf-8")

        self.assertIn("多角色蒸馏差分要求", prompt_text)
        self.assertIn("增量蒸馏规则", prompt_text)
        self.assertIn("request.update_mode", prompt_text)
        self.assertIn("request.existing_profiles", prompt_text)
        self.assertIn("这个角色与同批其他角色最不同的地方是什么", prompt_text)
        self.assertIn("共享场景优先用于提取 `key_bonds`", prompt_text)
        self.assertIn("输出前至少做一次区分度自检", prompt_text)
        self.assertIn("rules/character_hints/<novel_id>.md", prompt_text)

        self.assertIn("统一标尺", schema_text)
        self.assertIn("world_belong", schema_text)
        self.assertIn("rule_view", schema_text)
        self.assertIn("plot_restriction", schema_text)
        self.assertIn("appearance_feature", schema_text)
        self.assertIn("habit_action", schema_text)
        self.assertIn("interest_claim", schema_text)
        self.assertIn("resource_dependence", schema_text)
        self.assertIn("trade_principle", schema_text)
        self.assertIn("carry_style", schema_text)
        self.assertIn("disguise_switch", schema_text)
        self.assertIn("ooc_redline", schema_text)
        self.assertIn("evidence_source", schema_text)
        self.assertIn("contradiction_note", schema_text)
        self.assertIn("timeline_stage", schema_text)
        self.assertIn("relation_change", schema_text)
        self.assertIn("hidden_attitude", schema_text)
        self.assertIn("原作优先原则", schema_text)
        self.assertIn("公平蒸馏规则", schema_text)

        self.assertIn("原作优先", validation_text)
        self.assertIn("差分校验", validation_text)
        self.assertIn("evidence_source", validation_text)
        self.assertIn("interest_claim", validation_text)

    def test_skill_version_is_synced_across_metadata_and_release_docs(self):
        skill_dir = Path("clawhub-zaomeng-skill")
        version = read_skill_version(skill_dir)
        metadata = json.loads((skill_dir / ".metadata.json").read_text(encoding="utf-8"))
        skill_text = (skill_dir / "SKILL.md").read_text(encoding="utf-8")
        readme_text = (skill_dir / "README.md").read_text(encoding="utf-8")
        readme_en_text = (skill_dir / "README_EN.md").read_text(encoding="utf-8")
        publish_text = (skill_dir / "PUBLISH.md").read_text(encoding="utf-8")
        prompts_payload = json.loads((skill_dir / "examples" / "test-prompts.json").read_text(encoding="utf-8"))

        self.assertEqual(metadata["version"], version)
        self.assertIn(f"`{version}`", skill_text)
        self.assertIn(f"`{version}`", readme_text)
        self.assertIn(f"`{version}`", readme_en_text)
        self.assertIsNotNone(re.search(rf"^- Version:\s*{re.escape(version)}\s*$", publish_text, re.MULTILINE))
        self.assertEqual(prompts_payload["version"], version)


if __name__ == "__main__":
    unittest.main()
