#!/usr/bin/env python3
# -*- coding: utf-8 -*-

from .novel_preparation import build_excerpt_payload, load_prepared_novel_excerpt, prepare_novel_excerpt
from .persona_bundle import load_existing_persona_bundle, load_profile_source, materialize_persona_bundle, parse_profile_markdown
from .prompt_payloads import build_distill_prompt_payload, build_relation_prompt_payload
from .relation_graph_export import export_relation_graph
from .dialogue_payloads import (
    build_dialogue_suggestion_llm_messages,
    build_dialogue_suggestion_payload,
    compact_dialogue_suggestion_payload,
    normalize_dialogue_suggestion_context,
    parse_dialogue_suggestion,
)
from .scene_recommendations import (
    build_scene_opening_message,
    build_scene_recommendation_bundle,
    normalize_scene_recommendation_context,
    recommend_dialogue_scene_cards,
    recommend_scene_cards_base,
)
from .persona_review import (
    PERSONA_AUTOFILLABLE_FIELDS,
    PERSONA_REVIEW_ADVANCED_GROUPS,
    PERSONA_REVIEW_FIELD_LABELS,
    PERSONA_REVIEW_FIELDS,
    PERSONA_REVIEW_KEY_FIELDS,
    SELF_CARD_FIELDS,
    SELF_CARD_REQUIRED_FIELDS,
    SELF_CARD_FIELD_LABELS,
    apply_persona_review_updates,
    blank_self_card_fields,
    build_persona_field_completion_messages,
    build_persona_field_retry_messages,
    build_random_self_card_messages,
    delete_self_card_payload,
    list_self_cards_payload,
    load_persona_review_payload,
    load_self_card_payload,
    normalize_self_card_fields,
    parse_persona_field_completion_response,
    parse_random_self_card_response,
    read_persona_review_fields,
    resolve_persona_review_source,
    save_persona_review_profile,
    save_self_card_payload,
    validate_self_card_fields,
)
from .workflow_completion import (
    STANDARD_PROGRESS_STAGES,
    build_capability_status,
    build_persona_completion_status,
    build_relation_completion_status,
    default_status_path,
    infer_novel_id,
    initialize_run_manifest,
    update_run_manifest,
    verify_host_workflow,
)

__all__ = [
    "build_excerpt_payload",
    "load_prepared_novel_excerpt",
    "prepare_novel_excerpt",
    "build_distill_prompt_payload",
    "build_relation_prompt_payload",
    "load_existing_persona_bundle",
    "load_profile_source",
    "materialize_persona_bundle",
    "parse_profile_markdown",
    "export_relation_graph",
    "PERSONA_AUTOFILLABLE_FIELDS",
    "PERSONA_REVIEW_ADVANCED_GROUPS",
    "PERSONA_REVIEW_FIELD_LABELS",
    "PERSONA_REVIEW_FIELDS",
    "PERSONA_REVIEW_KEY_FIELDS",
    "SELF_CARD_FIELDS",
    "SELF_CARD_REQUIRED_FIELDS",
    "SELF_CARD_FIELD_LABELS",
    "apply_persona_review_updates",
    "blank_self_card_fields",
    "build_persona_field_completion_messages",
    "build_persona_field_retry_messages",
    "build_random_self_card_messages",
    "build_dialogue_suggestion_llm_messages",
    "build_dialogue_suggestion_payload",
    "build_scene_opening_message",
    "build_scene_recommendation_bundle",
    "compact_dialogue_suggestion_payload",
    "delete_self_card_payload",
    "list_self_cards_payload",
    "load_persona_review_payload",
    "load_self_card_payload",
    "normalize_dialogue_suggestion_context",
    "normalize_scene_recommendation_context",
    "normalize_self_card_fields",
    "parse_dialogue_suggestion",
    "parse_persona_field_completion_response",
    "parse_random_self_card_response",
    "read_persona_review_fields",
    "recommend_dialogue_scene_cards",
    "recommend_scene_cards_base",
    "resolve_persona_review_source",
    "save_persona_review_profile",
    "save_self_card_payload",
    "STANDARD_PROGRESS_STAGES",
    "build_capability_status",
    "build_persona_completion_status",
    "build_relation_completion_status",
    "default_status_path",
    "infer_novel_id",
    "initialize_run_manifest",
    "update_run_manifest",
    "verify_host_workflow",
    "validate_self_card_fields",
]
